  export var cities: string[] = [
    'Beograd',
    'Novi Sad',
    'Kraljevo',
    'Kragujevac',
    'Jagodina',
    'Mladenovac',
    'Subotica',
    'Ruma',
    'Priboj',
    'Sabac',
    'Leskovac',
    'Vranje',
    'Smederevo',
    'Pozarevac',
    'Zrenjanin',
    'Sombor',
  ];